apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-epouvante
  labels:
    app: backend-epouvante
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-epouvante  # NE PAS CHANGER : immutable
  template:
    metadata:
      labels:
        app: backend-epouvante
    spec:
      containers:
        - name: backend-epouvante
          image: monregistreepouvante.azurecr.io/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"