apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-epouvante
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-epouvante
  template:
    metadata:
      labels:
        app: backend-epouvante
    spec:
      containers:
        - name: backend
          image: monregistreepouvante.azurecr.io/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "production"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY