apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazar-api-gke-ingress
  annotations:
    networking.gke.io/managed-certificates: "bazar-api-cert"
    networking.gke.io/v1beta1.FrontendConfig: "bazar-https-redirect"
spec:
  ingressClassName: gce
  rules:
    - host: petite-maison-eprouvante.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bazar-api
                port:
                  number: 80
