apiVersion: v1
kind: Service
metadata:
  name: backend-epouvante
spec:
  type: NodePort
  selector:
    app: backend-epouvante
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001